---
- name: nginx install & start sercice 
  hosts: all 
  become: true

  tasks:
  - name: install nginx
    yum:
       name: httpd
       state: latest
  
  - name: start nginx
    service: 
      name : httpd
      state: stopped
